### ISSUE TITLE
[Build] 프로젝트 생성 및 코드기반 프로그래밍 세팅

### ISSUE THREAD

**Issue by ejalice** [ReadyToGoo/ReadyToGo_iOS#1]
**Issue : Feature**
XCode 프로젝트 생성 및 코드기반 프로그래밍 세팅 필요.

**Description**
1. Xcode 프로젝트 생성.
2. 코드기반 프로그래밍 세팅 설정.
3. Swift Package Manager를 통해 SnapKit 프레임워크 설치.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] Xcode 프로젝트 생성
- [x] 코드기반 프로그래밍 세팅 설정
- [x] Swift Package Manager를 통한 SnapKit 프레임워크 설치

**Reference(Optional)**
SnapKit : [Link](https://github.com/SnapKit/SnapKit)
