### ISSUE TITLE
[Feat] 탐색 탭 메인 페이지 + 알림 탭 구현

### ISSUE THREAD

**Issue by FpRaArNkK** [ReadyToGoo/ReadyToGo_iOS#10]
**Issue : Feature**
습관 탐색 탭의 메인페이지를 구현하고, 알림 탭을 구현합니다.

**Description**
-

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 검색하기 부분 확정 후 구현
- [x] 친구들 CollectionView 구현
- [x] SegmentControl 구현 
- [x] 습관 리스트 CollectionView 구현
- [x] ScrollVIew 구현 후 Views 등록
- [x] Scroll내리며 검색하기 / 습관 카테고리 리스트 상단 고정하기
- [x] 알림 탭 TableView 구현
- [x] Action 연결

**Reference(Optional)**
lo-fi 버전 구현입니다.
