### ISSUE TITLE
[Feat] WaitingView 구현

### ISSUE THREAD

**Issue by ejalice** [ReadyToGoo/ReadyToGo_iOS#30]
**Issue : Feature**
사용자가 홈 화면에서 '참여하기' 버튼을 누를 경우 이동하는 화면 구현.

**Description**
- 상단 문구 생성
- 시간이 지남에 따라 5에서부터 countdown.
- countdown 완료시 화면 이동.
- 하단 ScrollView(좌우) 구현

**Todo**
- [x] phraseLabel 생성: 상단 문구
- [x] CountDown Label 생성
- [x] CountDown 함수 구현
- [x] CountDown 완료시 화면 전환 함수 구현
- [x] 좌우 ScrollView 생성

**Reference(Optional)**
- 배경 아이콘, 화면 중앙 로고 그리고 화면 블러처리는 추후에 처리 예정.
