### ISSUE TITLE
[Feat] ParticipatingView 구현

### ISSUE THREAD

**Issue by ejalice** [ReadyToGoo/ReadyToGo_iOS#33]
**Issue : Feature**
유저가 습관에 참여하고 있을 때의 화면 구현.

**Description**
상단 문구, 투표까지 남은 시간 카운트다운, 참여자 프로필 이미지 및 이름, 촬영 버튼 UI 구현.

**Todo**
- [x] 상단 문구 Label 생성 - 이전 뷰(WaitingView)의 코드 재사용
- [x] CountDown Label 및 기능 생성
- [x] CountDown 완료시 화면 자동 화면 전환 구현
- [x] 참여자 프로필 이미지 및 이름 재사용 가능한 View 생성
- [ ] 참여자 수에 따른 프로필 및 이름 배치 기능 생성
- [x] 촬영 화면으로 이동 가능한 버튼 생성
- [x] 사진 및 영상 촬영 기능 구현

**Reference(Optional)**
습관 인증 시간이 지난 후의 화면 (다른 유저 사진/영상 확인 + 투표 화면)은 새로운 Issue 생성하여 작업할 예정.
