### ISSUE TITLE
[Feat] 습관 개설 Hi-Fi 수정 작업 + 습관 찾기 알림 탭 Hi-Fi 작업

### ISSUE THREAD

**Issue by FpRaArNkK** [ReadyToGoo/ReadyToGo_iOS#36]
**Issue : Feature**
습관 개설 Hi-Fi를 디자인 분과 함께 수정 작업합니다.
습관 찾기 알림 탭 Hi-Fi 작업 진행합니다.

**Description**

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 습관 개설 Hi-Fi 디자인 컨펌
- [x] 습관 찾기 알림탭 Hi-Fi 구현
- [x] 습관 찾기Hi-Fi 디자인 컨펌

**Reference(Optional)**
알림탭은 푸시 알림 기능 미구현으로 없는 화면을 기본으로 가집니다.
TableView는 유지한 상태로, 푸쉬 알림 기능이 진행되면 바로 Hi-Fi 진행하면 됩니다.
