### ISSUE TITLE
[Feat] HomeViewController Layout 구현

### ISSUE THREAD

**Issue by ejalice** [ReadyToGoo/ReadyToGo_iOS#5]
**Issue : Feature**
시간 및 습관 문구 및 좌우로 Swipe 가능한 Card 및 TimeLine을 구현해야 합니다.
**Description**
1. 시간 및 습관 UILabel 생성.
2. 좌우로 Swipe 가능한 Card 생성
3. Side Bar 구현

**Todo**
- [x] 시간 UILabel 생성
- [x] 습관 UILabel 생성
- [x] Carousel Layout 구현
- [x] TimeLine Layout 구현

**Reference(Optional)**
- Card 내부 Layout은 추후 LoFi가 완성되면 구현할 예정.
- 습관과 시간은 현재 고정된 Text 값이며, 추후 API 연결시 변경 예정.
