### ISSUE TITLE
[Feat] Vote 화면

### ISSUE THREAD

**Issue by ejalice** [ReadyToGoo/ReadyToGo_iOS#53]
**Issue : Feature**
참여자 중 베스트 습관러를 선택하는 화면 구현

**Description**
베스트 습관러를 선택하는 화면 구현.
ParticipatingView에서 사용했던 ParticipatingMemberViewCell을 활용해서 구현해볼 예정입니다.
만약 활용을 못할시에는 새로운 Cell을 작성하여 구현 예정.

**Todo**
- [x] 문구 생성
- [x] 버튼 생성 및 선택에 따른 활성화 비활성화
- [x] ParticipatingMemberViewCell 변형 or 새로 구현
- [x] 해당 Cell활용하여 VoteViewController에 CollectionView 띄우기
- [x] VoteViewController에서 유저가 Cell 선택시에 대한 Action 주기

**Reference(Optional)**
