### ISSUE TITLE
[Feat]BrowsingViewController 구현

### ISSUE THREAD

**Issue by thisisminseon** [ReadyToGoo/ReadyToGo_iOS#6]
**Issue : Feature**
NavigationBar의 하단 부터 TableView를 생성하고 카테고리, 습관 CollectionView를 배치합니다.

**Description**
1. TableView 생성
2. Search Button -> 디자이너 확인 후 디테일하게 구현
3. '친구들은요'부분은 CollectionView(Vertical)로 생성
4. '카테고리, 습관'은 각각 CollectionView(Vertical, Horizontal)로 생성

**Todo**

- [ ] 검색하기 아래부터 전체적 TableView 생성
- [ ] 검색하기 Button (디자이너 확인 필요)
- [ ] 카테고리 CollectionView(Vertical)
- [ ] 습관 CollectionView(horizontal)

**Reference(Optional)**
검색 View는 추후 디자인에 따라 구현될 예정입니다.
