### ISSUE TITLE
[Feat] AuthAPI, myInfo Manager  로그인 플로우와 연결

### ISSUE THREAD

**Issue by FpRaArNkK** [ReadyToGoo/ReadyToGo_iOS#60]
**Issue : Feature**
myInfo에 토큰 확인을 위한 여러 기능을 추가하고
화면 시작시 토큰 확인하여 홈 or 회원가입 플로우로 랜딩하는 과정을 진행합니다.

**Description**
작업사항에 대한 설명을 작성해주세요

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] myInfo 토큰 확인
- [x] myInfo userStatus 확인
- [x] VC에서 토큰 확인 후 , 분기점에서 각 VC로 present

**Reference(Optional)**
