### ISSUE TITLE
[Feat] 습관 찾기 Flow API 연결

### ISSUE THREAD

**Issue by FpRaArNkK** [ReadyToGoo/ReadyToGo_iOS#63]
**Issue : Feature**
습관 찾기 Flow에 서버 API를 연결합니다.
+ 습관 검색의 최근 검색어 내역을 UserDefault로 전환합니다.

**Description**
습관 탐색 VC API 연결
습관 최근 검색어 VC API 연결
습관 검색 결과 VC API 연결

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] HabitDiscoverViewController - MemberCollectionViewCell API Data Fetch
- [x] HabitDiscoverViewController - segmentCollectionViewCell API Data Fetch
- [x] HabitDiscoverViewController - HabitCardCollectionViewCell API Data Fetch
- [x] HabitCardCollectionViewCell - default Category 이미지, 텍스트 설정
- [x] SearchViewController - 최근 검색어 UserDefault 전환
- [x] SearchResultViewController - 유저 검색 Cell API Data Fetch
- [x] SearchResultViewController - 습관 검색 Cell API Data Fetch
- [x] kingFisher 추가

**Reference(Optional)**
