### ISSUE TITLE
[Feat] 다른 사람 영상 확인 화면

### ISSUE THREAD

**Issue by ejalice** [ReadyToGoo/ReadyToGo_iOS#66]
**Issue : Feature**
다른 사람 영상 확인 화면 구현

**Description**
Cell을 Tap했을 때, 사용자의 정보를 가지고 새로운 화면을 띄워야함.

**Todo**
- [x] 다른 사람 영상 확인 화면 생성
- [x] ParticipatingMemberViewCell -> tapGesture 생성
- [x] ParticipatingMemberCollectionView -> Protocol 생성
- [x] VoteViewController -> 새로운 화면 띄우기 + memberView 추가
- [ ] 유저 프로필 및 이름 확인
- [x] 영상 전체화면 재생
- [x] 영상 재생 완료시 자동 dismiss
