### ISSUE TITLE
[Feat] 홈 메인 플로우 UI + API 연결

### ISSUE THREAD

**Issue by FpRaArNkK** [ReadyToGoo/ReadyToGo_iOS#68]
**Issue : Feature**
홈화면에서 시작하는 메인 플로우의 UI를 리파인하고, API를 연결합니다.

**Description**
HomeViewController
WaitingViewController
ParticipatingViewController(optional)

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 홈화면 UI 리파인
- [x] 홈화면 API 연결
- [ ] 대기화면 API 연결

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
