### ISSUE TITLE
[Feat/Build] SearchVC, SearchResultVC lo-fi 완성 + etc

### ISSUE THREAD

**Issue by FpRaArNkK** [ReadyToGoo/ReadyToGo_iOS#8]
**Issue : Feature**
습관 탐색, 습관 탐색 결과 뷰 컨트롤러의 내용을 lo-fi에 맞게 수정
+ etc

**Description**
작업사항에 대한 설명을 작성해주세요
습관 탐색, 습관 탐색 결과 뷰 컨트롤러의 내용을 lo-fi에 맞게 수정
기존에 존재하던 custom navigation bar class를 하나로 통합
Bottom Sheet를 lofi 용으로 구현

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] SearchViewController 최근 검색어 적용
- [x] SearchViewResultViewController 선택 강조선 적용
- [x] SearchViewResultViewController 정렬 버튼 적용
- [x] Custom navigation Bar 수정 통합
- [x] Bottom sheet 제작

**Reference(Optional)**
Pull 잘 되는지 확인해주세요..!
